AllCops:
  TargetRubyVersion: 3.1.2
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "tmp/*"
    - "spec/**/*"
    - "node_modules/**/*"
    - "config/**/*"
    - "app/admin/**/*"

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - lib/tasks/**/*
    - ./**/concerns/*
    - Rakefile
    - ./**/*.rake
    - spec/**/*.rb
    - config/**/*

Layout/LineLength:
  Max: 120

Style/SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/Documentation:
   Enabled: false

Style/HashEachMethods:
   Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Lint/SymbolConversion:
  Enabled: false